# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_linear_alpha_remap <- function(X, Y, mu, omega, c_pi, d_pi, mu_alpha, tau_alpha, tau_b, tau_e, update_order, max_iter, tol) {
    .Call(`_spexvb_fit_linear_alpha_remap`, X, Y, mu, omega, c_pi, d_pi, mu_alpha, tau_alpha, tau_b, tau_e, update_order, max_iter, tol)
}

